#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx git-branch-is -r "^(feat|fix|chore)/"

npm run test:unit 
npm run test:acceptance 
npx jest-coverage-badges
git add coverage/badge-lines.svg

npx lint-staged -q
